### ISSUE TITLE
Proposal peer review by EPIDATA

### ISSUE THREAD

**Issue by rozay-avb-dev** [INFO-526-FA24/project-2-t2c#1]
The following is the peer review of the project proposal by [Epidata]. The team members that participated in this review are :

[Yitian Qian] - @[YitianQian777]
⁠[Rohit Surya AVB] - @[rozay_avb_dev]
⁠[Meghana Maringanti] - @[Meghana-Maringanti]
⁠⁠[Li Mi] - @[LiMi686]

**1. Describe the goal of the project.**

The goal of this project is to explore the health trend in Kenya and compare it to global patterns for the recent three decades.

**2. Describe the data used or collected.**

They are going to use multiple datasets, which include Kenyan Population Data, Global and Kenyan Suicide Rates Data, Mortality Data for Critical Diseases, Alcohol and Substance Use Data and Anxiety Disorder Prevalence Data.

**3. Describe how the research question will be answered, e.g. what approaches / methods will be used.**

They did not specify their research questions or the methods and approaches. They may need to add this section to their proposal.

**4. Is there anything that is unclear from the proposal?**

As the question above mentioned, they didn’t mention the primary research questions that they aim to answer using this question, so this is the most unclear part. In addition, in the weekly plan of attack, the assignee for all tasks is team. But maybe they do plan to have everyone do all the tasks together, so they don’t need to change it if this is the case, but if they do plan to have different members do different tasks, it is better to specify them.

**5. Provide constructive feedback on how the team might be able to improve their project.**

Since they did not have the section of research questions and how they are going to do them, we don’t have the starting point of how to improve on the project. The feedback right now is mainly on how to improve the proposal first.

**6. What aspect of this project are you most interested in and would like to see highlighted in the presentation.**

I am most interested in seeing the gender-specific analysis of mental health trends. Highlighting differences in how men and women in Kenya are affected by suicide rates and anxiety disorders compared to global patterns would provide valuable context for targeted public health strategies.

**7. Provide constructive feedback on any issues with file and/or code organization.**

Issues:
Add a ReadMe file for the project. 
Add about section in readme or about.qmd to include your Team details. 
Add sources for the data, preferably add as embedded links.
Add “Research Questions” section include - question and methods/visualizations used to answer the questions
Add Assignees and adjust the timelines accordingly.
All sections starting from the “Project Repository Organization” can be moved to a ReadMe file (not required in Proposal)

**Comment by SaikumarBollam** [comment]
Addressed issues thank you !!
