### ISSUE TITLE
Proposal Peer Review By Data Detectives

### ISSUE THREAD

**Issue by AmanSingh0512** [INFO-526-FA24/project-2-t2c#2]
The following is the peer review of the project proposal by T2C. The team members that participated in this review are

Aman, Singh - @AmanSingh0512

Hema Priya Prakash - @hema2101UoA

Swetha, Kolloju - @swethakolloju1

~ Team Data Detectives 	

---Describe the goal of the project.

The goal of this project is to create an interactive visualization of Kenyan and global health trends, focusing on metrics such as population demographics, suicide rates, critical disease mortality, alcohol and substance use, and anxiety disorder prevalence. By examining these trends, particularly with a gender-specific lens, the project aims to reveal insights into the health landscape in Kenya compared to global patterns. These visualizations will provide valuable information for researchers, policymakers, and the general public, aiding in understanding key health challenges and informing strategies for public health and social stability.

---Describe the data used or collected..

The data for this project covers key health metrics for Kenya and global populations. It includes Kenyan population data to assess demographic shifts, global and Kenyan suicide rates (2000-2019) with gender breakdowns, and mortality data for major diseases like cardiovascular disease, cancer, diabetes, and respiratory diseases (2000-2016). Additionally, it features data on alcohol and substance use trends (1990-2019) and gender-specific anxiety disorder prevalence, providing mental health insights. These datasets will be cleaned and processed to enable consistent and insightful analysis for visualization.

---Describe how the research question will be answered, e.g. what approaches / methods will be used.

1.  How have suicide rates evolved globally and in Kenya from 2000 to 2019, and what are the gender-specific differences in these trends?
•	Method: Time-series analysis with line graphs to compare trends in suicide rates by gender for Kenya and globally.
2. What are the differences in mortality probabilities from critical diseases (e.g., cardiovascular diseases, cancer, diabetes, and chronic respiratory diseases) between global populations and the Kenyan population between 2000 and 2016?
•	Method: Line and bar charts to visualize mortality probabilities for these diseases, focusing on gender-based comparisons between Kenya and global statistics.
3. How do trends in alcohol and substance use disorders differ globally compared to Kenya from 1990 to 2019, and what are the implications of these trends on public health in Kenya?
•	Method: Line plots and histograms to compare substance use trends over time, providing insights into potential public health implications in Kenya.
4. What is the prevalence of anxiety disorders globally and in Kenya from 1990 to 2019, and how do gender-specific trends inform our understanding of mental health challenges in these regions?
•	Method: Bar plots and line charts to examine anxiety disorder prevalence by gender, comparing Kenyan and global trends.
5. What impact has population growth and age distribution had on the labor potential in Kenya from 1990 to 2019, and how does this compare to global trends in workforce development?
•	Method: Population pyramids and age distribution histograms to analyze demographic shifts affecting Kenya's labor force, with comparisons to global trends.
6. What socio-economic and cultural factors might explain the observed differences in health trends (suicide rates, critical disease mortality, anxiety, and substance use) between genders in Kenya compared to global averages over the last three decades?
•	Method: Correlation analysis and scatter plots to identify socio-economic and cultural factors that may influence observed gender-specific health disparities between Kenya and global averages.

---Is there anything that is unclear from the proposal?

The proposal is well-structured, but a few clarifications would strengthen it. First, it would help to specify the socio-economic factors included in the dataset or whether additional data is needed to analyze cultural drivers behind health trends. Second, addressing how differences in dataset time ranges will be managed, either by focusing on overlapping years or using imputation, would improve clarity. Finally, specifying which global sources will be used for comparison and how they ensure consistent metrics with Kenyan data would enhance the analysis plan.

---Provide constructive feedback on how the team might be able to improve their project.

As mentioned above Visualization choices would greatly help with understanding the though process for the project.
Visualizations: The proposal could mention specific types of visualizations (e.g., line charts, bar graphs) that will be used to present findings, especially for questions like shot accuracy and disciplinary records.

---Further cleaning data would ensure the data quality which could be leveraged to build advanced models.

1.  Standardize the timeframes across datasets or use imputation to ensure consistent comparisons in trends.
2. Expand the socio-economic analysis by incorporating additional variables like income, healthcare access, or education to provide deeper context.

---What aspect of this project are you most interested in and would like to see highlighted in the presentation.

We are most interested in the comparison of gender-specific health trends, particularly in areas like suicide rates, anxiety disorders, and substance use, both in Kenya and globally. Highlighting these differences could reveal important insights into mental health challenges and inform public health strategies. It would be great to see how these trends evolve over time and the socio-economic factors influencing them, as well as how the data visualizations effectively communicate these disparities.

---Provide constructive feedback on any issues with file and/or code organization.

To improve code organization, they can keep the folder structure clear by separating raw and processed data and adding README files for guidance. Break the code into smaller, easy-to-understand functions, and adding comments to explain key steps..

Thanks, We loved your Proposal, Best of luck for your project :)

~ Team Data Detectives

**Comment by SaikumarBollam** [comment]
Addressed issues thank you !!
