### ISSUE TITLE
Instructor Review 

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-t2c#3]
Hello team Insight Decoders 

Overall, your proposal indicates that you are set up for a success. You have a data set that will be able to answer the research questions through the proposed analysis and visualizations. Just be sure that you are doing original work. 

From peer review - I do not see a README file? 

Note that everyone should be active in GitHub and contributing to the project.  There are no commits by Vamsi.

One area of consideration that I do not see is addressed int he proposal is the approach to the poster presentation. As a team, spend some time storyboarding the poster and consider how such an ambitious project will be translated into a poster.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |      3  |
| Proposal | 5         |    5    |
| Workflow | 1         |    1    |
| Teamwork | 1         |     0   |
| Total    | 10        |   9    |

**Comment by vkrishna-1** [comment]
Hello Professor,

Initially we have collaborate our works and pushed it at once. So, my(Vamsi) commits were not there. From now on we will commit separately.
We have also added README.md file in the repository. Thank you
