### ISSUE TITLE
Review from DataWaves

### ISSUE THREAD

**Issue by Saharsh-Bhave** [INFO-526-FA24/project-2-t2c#5]
### 1. What is the good thing in the poster?
The topic this team has chosen is analyzing Brexit data. They chosen good visualizations to appropriately display their data.

### 2. What do you think can/should be improved?
The poster can be rearranged in such a way that their visualizations are clearer to the audience.

**Comment by SaikumarBollam** [comment]
The chosen topic and visualizations effectively present the Brexit data. However, the layout could be rearranged to make the visualizations clearer to the audience.
